### PR TITLE
added language template for Germany aka de_DE

### PR DESCRIPTION
**Pull request by k0pernikus**
A quoted message will look like this for German:
```
This mail quotes a text!

Am 21.10.2015 um 17:48 hat Philipp Kretzschmar geschrieben:
> quote this text

-- 
signature_content
```

### CODE REVIEW

**Comment by k0pernikus** [comment]
I just found out that the `sent items` entry is for the imap functionality to access the sent entries, and for my case *must not* be translated, as it stops working then. (Still sends mails, they cannot be seen in the sent folder.)

I have my office365 in english langauge, will have to look up if there are changes for de_DE. 

This pull request as is, breaks the sent items functionality when using the German locale.

**Comment by ork** [comment]
Thanks for the PR.

If I understood, the name of the IMAP directories depend on the locale set in the web UI? That's crazy. Well, not much more than giving them weird and translatable names anyway.

I will merge this soon.

**Comment by k0pernikus** [comment]
@ork I am not sure if it's defined by the UI locale or on the server side, which for me is using the English names. 

From the way the config file was setup I also did not entirely understand what those directory specific phrases meant and am unsure that my translation of those IMAP folders are the actual German translation. I have to look into this further.

Maybe one can explicate that part in the `Readme.md`, and maybe we should split the locale setting about placeholder texts and the locale setting about the IMAP folders, as those can differ, e.g. I want English locale, yet German phrases.

**Comment by k0pernikus** [comment]
I just checked with the German version of the Web UI and updated the folder names. Still, as it stands the config does not support mixed locale of Web UI and intended layout of the mail, but I guess that is a different issue entirely =)

**Comment by k0pernikus** [comment]
Thanks for merging :dancers:

**Pull request merged**
